import Head from "next/head";

import styles from "../../styles/Home.module.css";
import { paginate } from "../helpers/paginate";

export default function Home( {data, currentPage, pageSize}) {


  const paginatedPosts = paginate(data, currentPage, pageSize);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>
        <strong>NextJS x Pagination x Go Back x Go Forward</strong>
      </p>
      <p>
        Page: <span style={{ color: "red" }}>{currentPage}</span>
      </p>

      {paginatedPosts.map((item) => {
        return <p key={item.id}>{item.title}</p>;
      })}

    </div>
  );
}